import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin, Music2, Music2Off, ArrowRight, Heart, Menu, X, ChevronLeft, ChevronRight} from 'lucide-react';
import {wedding as w} from './config';
import './style.css';
const date = new Date(w.dateISO);
function countdown(){const n=Math.max(0,date.getTime()-Date.now());return [Math.floor(n/86400000),Math.floor(n/3600000)%24,Math.floor(n/60000)%60,Math.floor(n/1000)%60]}
function App(){
 const [remaining,setRemaining]=useState(countdown()); const [menu,setMenu]=useState(false);const [music,setMusic]=useState(false);const [lightbox,setLightbox]=useState(-1);const audio=useRef(null);
 const [form,setForm]=useState({name:'',email:'',attendance:'yes',guests:'1',dietary:'',message:''});const [status,setStatus]=useState('');const [sending,setSending]=useState(false);
 useEffect(()=>{const id=setInterval(()=>setRemaining(countdown()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{function key(e){if(e.key==='Escape')setLightbox(-1);if(e.key==='ArrowRight')setLightbox(x=>x<0?x:(x+1)%w.photos.length);if(e.key==='ArrowLeft')setLightbox(x=>x<0?x:(x+w.photos.length-1)%w.photos.length)}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 async function toggleMusic(){if(!audio.current)return;try{if(music){audio.current.pause();setMusic(false)}else{await audio.current.play();setMusic(true)}}catch{setStatus('Add public/music.mp3 to enable music.')}}
 async function submit(e){e.preventDefault();setSending(true);setStatus('');try{const res=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)throw Error(data.error||'Unable to submit RSVP');setStatus('Thank you! Your RSVP has been received.');setForm({name:'',email:'',attendance:'yes',guests:'1',dietary:'',message:''})}catch(err){setStatus(err.message)}finally{setSending(false)}}
 const nav=[['Our Story','#story'],['The Day','#details'],['Gallery','#gallery'],['RSVP','#rsvp']];
 return <><header className="nav"><a href="#home" className="monogram">{w.couple.map(x=>x[0]).join(' & ')}</a><nav className={menu?'open':''}>{nav.map(([t,l])=><a key={l} href={l} onClick={()=>setMenu(false)}>{t}</a>)}</nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button></header>
 <main><section className="hero" id="home"><div className="hero-border"><div className="eyebrow">JOYFULLY INVITE YOU TO CELEBRATE</div><div className="ornament">✦</div><h1>{w.couple[0]}<span>&</span>{w.couple[1]}</h1><p className="script">Together is a beautiful place to be</p><div className="rule"/><p className="hero-date">{w.dateDisplay} <span>·</span> {w.location}</p><a href="#rsvp" className="btn gold">KINDLY RSVP <ArrowRight size={16}/></a></div><div className="hero-bottom">SCROLL TO EXPLORE <span>↓</span></div></section>
 <section className="intro section" id="story"><div className="eyebrow">THE BEGINNING OF FOREVER</div><h2>Our Love Story</h2><div className="flourish">❧</div><p>{w.heroMessage}</p><p>We cannot wait to share this beautiful moment with the people who mean the most to us.</p><Heart size={22} strokeWidth={1} className="heart"/></section>
 <section className="countdown section"><div className="eyebrow">COUNTING DOWN TO OUR SPECIAL DAY</div><h2>Until We Say “I Do”</h2><div className="digits">{remaining.map((v,i)=><div key={i}><strong>{String(v).padStart(2,'0')}</strong><small>{['DAYS','HOURS','MINUTES','SECONDS'][i]}</small></div>)}</div></section>
 <section className="section details" id="details"><div className="eyebrow">YOU ARE CORDIALLY INVITED</div><h2>The Wedding Day</h2><p className="section-lead">A day filled with love, joy and beautiful memories.</p><div className="venue-grid">{[w.ceremony,w.reception].map((v,i)=><article className="venue" key={i}><div className="venue-symbol">{i?'✧':'✦'}</div><div className="eyebrow">{v.time}</div><h3>{v.title}</h3><strong>{v.venue}</strong><p>{v.address}</p><a className="text-link" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(v.mapQuery)} target="_blank" rel="noreferrer"><MapPin size={16}/> GET DIRECTIONS</a><iframe title={v.title+' map'} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={'https://maps.google.com/maps?q='+encodeURIComponent(v.mapQuery)+'&output=embed'}/></article>)}</div></section>
 <section className="section timeline"><div className="eyebrow">THE ORDER OF EVENTS</div><h2>Wedding Schedule</h2><div className="timeline-items">{w.schedule.map((s,i)=><div className="timeline-item" key={i}><time>{s.time}</time><div className="dot"/><div><h3>{s.event}</h3><p>{s.detail}</p></div></div>)}</div></section>
 <section className="section gallery" id="gallery"><div className="eyebrow">MOMENTS TO TREASURE</div><h2>Our Gallery</h2><p className="section-lead">A few moments from our journey together.</p><div className="photos">{w.photos.map((src,i)=><button className="photo" key={src} onClick={()=>setLightbox(i)} aria-label={'Open photo '+(i+1)}><img src={src} alt={'Couple photo '+(i+1)} onError={e=>{e.currentTarget.style.opacity='0'}}/><span>VIEW PHOTO {i+1}</span></button>)}</div><p className="photo-note">Replace the four sample photo files in public/photos with your own images.</p></section>
 <section className="section rsvp" id="rsvp"><div className="rsvp-panel"><div className="eyebrow">THE PLEASURE OF YOUR COMPANY</div><h2>Kindly RSVP</h2><p>We would be honoured to celebrate with you.<br/>Please respond by {new Date(w.rsvpDeadline+'T12:00:00').toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'})}.</p><form onSubmit={submit}><label>FULL NAME<input required maxLength="120" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your full name"/></label><label>EMAIL ADDRESS<input type="email" required maxLength="200" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>WILL YOU ATTEND?<select value={form.attendance} onChange={e=>setForm({...form,attendance:e.target.value})}><option value="yes">Joyfully accepts</option><option value="no">Regretfully declines</option></select></label>{form.attendance==='yes'&&<><label>NUMBER OF GUESTS (INCLUDING YOU)<select value={form.guests} onChange={e=>setForm({...form,guests:e.target.value})}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>DIETARY REQUIREMENTS<textarea maxLength="500" rows="2" value={form.dietary} onChange={e=>setForm({...form,dietary:e.target.value})} placeholder="Any allergies or dietary requirements?"/></label></>}<label>MESSAGE FOR THE COUPLE (OPTIONAL)<textarea rows="3" maxLength="1000" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Leave a little note..."/></label><button disabled={sending} className="btn gold submit" type="submit">{sending?'SENDING...':'SEND RSVP'} <ArrowRight size={16}/></button><p className="form-status" role="status">{status}</p></form></div></section></main>
 <footer><div className="footer-names">{w.couple.join(' & ')}</div><div className="flourish">✦</div><p>{w.dateDisplay}</p><small>MADE WITH LOVE · FOREVER STARTS HERE</small></footer>
 <audio ref={audio} src={w.musicFile} loop preload="none" onEnded={()=>setMusic(false)}/><button className="music" onClick={toggleMusic} aria-label={music?'Pause background music':'Play background music'} title={music?'Pause music':'Play music'}>{music?<Music2 size={20}/>:<Music2Off size={20}/>}</button>
 {lightbox>=0&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Photo viewer"><button className="close" onClick={()=>setLightbox(-1)} aria-label="Close"><X/></button><button onClick={()=>setLightbox((lightbox+w.photos.length-1)%w.photos.length)} aria-label="Previous photo"><ChevronLeft/></button><img src={w.photos[lightbox]} alt={'Couple photo '+(lightbox+1)}/><button onClick={()=>setLightbox((lightbox+1)%w.photos.length)} aria-label="Next photo"><ChevronRight/></button></div>}
 </>}
createRoot(document.getElementById('root')).render(<App/>);
